name: NasBuild

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout Nascraft source code
      - name: Checkout Nascraft
        uses: actions/checkout@v4
        with:
          repository: 'Bounser/Nascraft'
          path: nascraft-source
          fetch-depth: 0

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Build with Maven
      - name: Build with Maven
        working-directory: ./nascraft-source
        run: |
          mvn -B clean package -DskipTests \
              -Dmaven.compiler.source=21 \
              -Dmaven.compiler.target=21 \
              -Dmaven.compiler.release=21

      # Find the built JAR
      - name: Locate JAR
        id: locate-jar
        working-directory: ./nascraft-source
        run: |
          JAR_PATH=$(find target -name '*.jar' ! -name '*-tests.jar' ! -name 'original-*.jar' | head -1)
          echo "jar_name=${JAR_PATH##*/}" >> $GITHUB_OUTPUT
          echo "jar_path=$PWD/$JAR_PATH" >> $GITHUB_OUTPUT

      # Generate all date strings in advance
      - name: Generate dates
        id: dates
        run: |
          echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_UTC=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
          echo "RELEASE_BODY=$(printf 'Automated build of Nascraft\n- Source: https://github.com/Bounser/Nascraft\n- Commit: %s\n- Java: 21\n- Build date: %s' '${{ github.sha }}' '$(date -u +"%Y-%m-%d %H:%M:%S UTC")')" >> $GITHUB_ENV

      # Create release with precomputed values
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "auto-build-${{ env.TAG_DATE }}"
          name: "Nascraft At ${{ env.RELEASE_DATE }}"
          body: ${{ env.RELEASE_BODY }}
          files: |
            ${{ steps.locate-jar.outputs.jar_path }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
