name: NasBuild

on:
  schedule:
    - cron: '0 0 */2 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout Nascraft source code
      - name: Checkout Nascraft
        uses: actions/checkout@v4
        with:
          repository: 'Bounser/Nascraft'
          path: nascraft-source
          fetch-depth: 0

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Build with Maven
      - name: Build with Maven
        working-directory: ./nascraft-source
        run: |
          mvn -B clean package -DskipTests \
              -Dmaven.compiler.source=21 \
              -Dmaven.compiler.target=21 \
              -Dmaven.compiler.release=21

      # Find the built JAR
      - name: Locate JAR
        id: locate-jar
        working-directory: ./nascraft-source
        run: |
          JAR_PATH=$(find target -name '*.jar' ! -name '*-tests.jar' ! -name 'original-*.jar' | head -1)
          echo "jar_name=${JAR_PATH##*/}" >> $GITHUB_OUTPUT
          echo "jar_path=$PWD/$JAR_PATH" >> $GITHUB_OUTPUT

      # Generate dates using simplified approach
      - name: Generate release info
        id: release-info
        run: |
          # Simple date variables
          RELEASE_DATE=$(date +'%Y-%m-%d')
          TAG_DATE=$(date +'%Y%m%d')
          BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          
          # Create body without complex formatting
          BODY="Automated build of Nascraft"
          BODY+="\n- Source: https://github.com/Bounser/Nascraft"
          BODY+="\n- Commit: ${{ github.sha }}"
          BODY+="\n- Java: 21"
          BODY+="\n- Build date: $BUILD_DATE"
          
          # Set outputs
          echo "release_date=$RELEASE_DATE" >> $GITHUB_OUTPUT
          echo "tag_date=$TAG_DATE" >> $GITHUB_OUTPUT
          echo "body=$BODY" >> $GITHUB_OUTPUT

      # Create release with simplified values
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "auto-build-${{ steps.release-info.outputs.tag_date }}"
          name: "Nascraft At ${{ steps.release-info.outputs.release_date }}"
          body: ${{ steps.release-info.outputs.body }}
          files: |
            ${{ steps.locate-jar.outputs.jar_path }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
